In [2]:
import numpy as np



In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.full((4,6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(5) #to create identity matrix of order 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [10]:
np.linspace(0,1,5) #evenly spaced elements 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
myarr=np.array([[1,2,3],[5,4,7],[9,8,0]])

In [13]:
myarr.shape

(3, 3)

In [14]:
myarr.size

9

In [15]:
myarr.ndim

2

In [17]:
myarr.dtype #can explicitly define the datatype

dtype('int64')

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
