In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40
# same as python list

10
40


In [3]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [4]:
#Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

In [5]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [6]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


In [7]:

#MULTI-DIMENSIONAL INDEXING AND AXIS
#axis-> Each dimension in a NumPy array is called an axis. Axes are numbered starting from 0

In [9]:
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr2[0]

array([1, 2, 3])

In [12]:
arr2[1]


array([4, 5, 6])

In [14]:
print(np.sum(arr2, axis=0))  # Sum along rows (down each column)
print(np.sum(arr2, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [16]:
# Accessing an element
print(arr2[1, 2])  # Row index 1, Column index 2 → Output: 6

6


In [18]:
print(arr2[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [19]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [20]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [22]:
# Get all rows of the first column
first_col = arr3D[:, 0]
print(first_col)  # Output: [1 4 7]

[[1 2 3]
 [7 8 9]]


In [23]:
arr3D[:,0,:]=0

In [24]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])