In [1]:
import numpy as np
import time

size=1000000

#python list 
l1=list(range(size))
l2=list(range(size))
start=time.time()

add=[x+y for x,y in zip(l1,l2)]
end=time.time()
print("Time: ",end-start)

Time:  0.15883183479309082


In [4]:
#using numpy arrays
arr1=np.array(list(range(size)))
arr2=np.array(list(range(size)))
start=time.time()

add=arr1+arr2
end=time.time()
print("Time: ",end-start)

Time:  0.04945492744445801


In [10]:
# Numpy is faster than python list because it performs operations in C

In [11]:
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
 
# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
 
# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape) #shape will give the order of the array

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [12]:
#NumPy stores data in a contiguous memory block

In [13]:
#Let's check memory consumption
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [17]:
#NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

# Python list (loop-based)
list1=[1,2,3,4]
list_squares = [x ** 2 for x in list1]
print("Using python list :",list_squares)
# NumPy (vectorized)
arr1=np.array([1,2,3,4])
numpy_squares = arr1 ** 2
print("\nUsing numpy :",numpy_squares)

Using python list : [1, 4, 9, 16]

Using numpy : [ 1  4  9 16]
